Feat(trak): Add all tables for Trak
blankoslo/floq-db pull request #49
Opened 2022-04-27 20:37 UTC by Zenjjim

2022-04-28 06:36 UTC, maxschau commented
En annen ting; for å benytte oss av gen_random_uuid() må vi ha extensionen pgcrypto i databasen.
`create extension pgcrypto;` 
Er dette noe som skal ligge i sqitch-filen?

2022-04-28 07:18 UTC, JamiesWhiteShirt commented
Et annet verktøy jeg har brukt som gjør migrasjoner (Hasura) pleier å putte `CREATE EXTENSION IF NOT EXISTS pgcrypto;` på starten av migrasjoner som bruker `gen_random_uuid()`. Jeg ser derimot allerede bruk av `gen_random_uuid()` i eksisterende migrasjoner og ingen eksplisitt oppsett av pgcrypto, så da kan man nok anta at pgcrypto allerede er installert.

2022-04-28 07:47 UTC, JamiesWhiteShirt requested changes

2022-04-28 07:47 UTC, JamiesWhiteShirt commented on sqitch/revert/add_trak.sql
> +DROP TYPE responsible_type CASCADE;
Har du testet denne down-migrasjonen? Jeg tror ikke den fungerer. Eksempelvis slettes her `responsible_type` før `task`-tabellen, som bruker denne typen.

 Vanligvis undoer man endringene man har gjort i migrasjonen i motsatt rekkefølge.

2022-04-28 09:01 UTC, Zenjjim commented on sqitch/revert/add_trak.sql
> +DROP TYPE responsible_type CASCADE;
Jeg har revertet changesene og får ikke opp noen feilmeldinger nei, men kan godt flytten den under drop table :D

2022-04-29 10:37 UTC, JamiesWhiteShirt approved these changes

2022-04-29 12:56 UTC, merged